namespace: prom_alerts
groups:
    - name: cortex_alerts
      rules:
        - alert: "CortexIngesterUnhealthy"
          expr: |-
            min by(cluster, namespace) (cortex_ring_members{name="ingester",state="Unhealthy"}) > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            message: There are {{ printf "%f" $value }} unhealthy ingester(s).
        - alert: "CortexRequestErrors"
          expr: |-
            100 * sum by(cluster, namespace, job, route) (rate(cortex_request_duration_seconds_count{route!~"ready",status_code=~"5.."}[1m])) / sum by(cluster, namespace, job, route) (rate(cortex_request_duration_seconds_count{route!~"ready"}[1m])) > 1
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf "%.2f" $value }}% errors.
        - alert: "CortexRequestLatency"
          expr: |-
            cluster_namespace_job_route:cortex_request_duration_seconds:99quantile{route!~"metrics|/frontend.Frontend/Process|ready"} > 2.5
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                {{ $labels.job }} {{ $labels.route }} is experiencing {{ printf "%.2f" $value }}s 99th percentile latency.
        - alert: "CortexTableSyncFailure"
          expr: |-
            100 * rate(cortex_table_manager_sync_duration_seconds_count{status_code!~"2.."}[15m]) / rate(cortex_table_manager_sync_duration_seconds_count[15m]) > 10
          for: 30m
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.job }} is experiencing {{ printf "%.2f" $value }}% errors syncing tables.
        - alert: "CortexQueriesIncorrect"
          expr: |-
            100 * sum by(cluster, namespace) (rate(test_exporter_test_case_result_total{result="fail"}[5m])) / sum by(cluster, namespace) (rate(test_exporter_test_case_result_total[5m])) > 1
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                Incorrect results for {{ printf "%.2f" $value }}% of queries.
        - alert: "CortexInconsistentConfig"
          expr: |-
            count without(sha256) (count by(cluster, namespace, job, sha256) (cortex_config_hash)) > 1
          for: 1h
          labels:
            severity: warning
          annotations:
            message: |
                An inconsistent config file hash is used across cluster {{ $labels.job }}.
        - alert: "CortexBadRuntimeConfig"
          expr: |-
            cortex_runtime_config_last_reload_successful == 0 or cortex_overrides_last_reload_successful == 0
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                {{ $labels.job }} failed to reload runtime config.
        - alert: "CortexQuerierCapacityFull"
          expr: |-
            prometheus_engine_queries_concurrent_max{job=~".+/(cortex|ruler|querier)"} - prometheus_engine_queries{job=~".+/(cortex|ruler|querier)"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.job }} is at capacity processing queries.
        - alert: "CortexFrontendQueriesStuck"
          expr: |-
            sum by(cluster, namespace) (cortex_query_frontend_queue_length) > 1
          for: 5m
          labels:
            severity: critical
          annotations:
            message: |
                There are {{ $value }} queued up queries in query-frontend.
        - alert: "CortexSchedulerQueriesStuck"
          expr: |-
            sum by(cluster, namespace) (cortex_query_scheduler_queue_length) > 1
          for: 5m
          labels:
            severity: critical
          annotations:
            message: |
                There are {{ $value }} queued up queries in query-scheduler.
        - alert: "CortexCacheRequestErrors"
          expr: |-
            100 * sum by(cluster, namespace, method) (rate(cortex_cache_request_duration_seconds_count{status_code=~"5.."}[1m])) / sum by(cluster, namespace, method) (rate(cortex_cache_request_duration_seconds_count[1m])) > 1
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                Cache {{ $labels.method }} is experiencing {{ printf "%.2f" $value }}% errors.
        - alert: "CortexIngesterRestarts"
          expr: |-
            changes(process_start_time_seconds{job=~".+(cortex|ingester)"}[30m]) > 1
          labels:
            severity: critical
          annotations:
            message: '{{ $labels.job }}/{{ $labels.instance }} has restarted {{ printf "%.2f" $value }} times in the last 30 mins.'
        - alert: "CortexTransferFailed"
          expr: |-
            max_over_time(cortex_shutdown_duration_seconds_count{op="transfer",status!="success"}[15m])
          for: 5m
          labels:
            severity: critical
          annotations:
            message: '{{ $labels.job }}/{{ $labels.instance }} transfer failed.'
        - alert: "CortexOldChunkInMemory"
          expr: |-
            (time() - cortex_oldest_unflushed_chunk_timestamp_seconds > 36000) and (cortex_oldest_unflushed_chunk_timestamp_seconds > 0)
          for: 5m
          labels:
            severity: warning
          annotations:
            message: |
                {{ $labels.job }}/{{ $labels.instance }} has very old unflushed chunk in memory.
        - alert: "CortexMemoryMapAreasTooHigh"
          expr: |-
            process_memory_map_areas{job=~".+(cortex|ingester|store-gateway)"} / process_memory_map_areas_limit{job=~".+(cortex|ingester|store-gateway)"} > 0.8
          for: 5m
          labels:
            severity: critical
          annotations:
            message: '{{ $labels.job }}/{{ $labels.instance }} has a number of mmap-ed areas close to the limit.'
    - name: cortex_wal_alerts
      rules:
        - alert: "CortexWALCorruption"
          expr: |-
            increase(cortex_ingester_wal_corruptions_total[5m]) > 0
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.job }}/{{ $labels.instance }} has a corrupted WAL or checkpoint.
        - alert: "CortexCheckpointCreationFailed"
          expr: |-
            increase(cortex_ingester_checkpoint_creations_failed_total[10m]) > 0
          labels:
            severity: warning
          annotations:
            message: |
                {{ $labels.job }}/{{ $labels.instance }} failed to create checkpoint.
        - alert: "CortexCheckpointCreationFailed"
          expr: |-
            increase(cortex_ingester_checkpoint_creations_failed_total[1h]) > 1
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.job }}/{{ $labels.instance }} is failing to create checkpoint.
        - alert: "CortexCheckpointDeletionFailed"
          expr: |-
            increase(cortex_ingester_checkpoint_deletions_failed_total[10m]) > 0
          labels:
            severity: warning
          annotations:
            message: |
                {{ $labels.job }}/{{ $labels.instance }} failed to delete checkpoint.
        - alert: "CortexCheckpointDeletionFailed"
          expr: |-
            increase(cortex_ingester_checkpoint_deletions_failed_total[2h]) > 1
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.instance }} is failing to delete checkpoint.
    - name: cortex-provisioning
      rules:
        - alert: "CortexProvisioningMemcachedTooSmall"
          expr: |-
            (4 * sum by(cluster, namespace) (cortex_ingester_memory_series * cortex_ingester_chunk_size_bytes_sum / cortex_ingester_chunk_size_bytes_count) / 1e+09) > (sum by(cluster, namespace) (memcached_limit_bytes{job=~".+/memcached"}) / 1e+09)
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                Chunk memcached cluster is too small, should be at least {{ printf "%.2f" $value }}GB.
        - alert: "CortexProvisioningTooManyActiveSeries"
          expr: |-
            avg by(cluster, namespace) (cortex_ingester_memory_series) > 1.6e+06 and sum by(cluster, namespace) (rate(cortex_ingester_received_chunks[1h])) == 0
          for: 1h
          labels:
            severity: warning
          annotations:
            message: |
                Too many active series for ingesters, add more ingesters.
        - alert: "CortexProvisioningTooManyWrites"
          expr: |-
            avg by(cluster, namespace) (rate(cortex_ingester_ingested_samples_total[1m])) > 80000
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                High QPS for ingesters, add more ingesters.
        - alert: "CortexAllocatingTooMuchMemory"
          expr: |-
            (container_memory_working_set_bytes{container="ingester"} / container_spec_memory_limit_bytes{container="ingester"}) > 0.5
          for: 15m
          labels:
            severity: warning
          annotations:
            message: |
                Too much memory being used by {{ $labels.namespace }}/{{ $labels.pod }} - add more ingesters.
        - alert: "CortexAllocatingTooMuchMemory"
          expr: |-
            (container_memory_working_set_bytes{container="ingester"} / container_spec_memory_limit_bytes{container="ingester"}) > 0.8
          for: 15m
          labels:
            severity: critical
          annotations:
            message: |
                Too much memory being used by {{ $labels.namespace }}/{{ $labels.pod }} - add more ingesters.
    - name: ruler_alerts
      rules:
        - alert: "CortexRulerFailedEvaluations"
          expr: |-
            sum by(cluster, namespace, instance, rule_group) (rate(cortex_prometheus_rule_evaluation_failures_total[1m])) / sum by(cluster, namespace, instance, rule_group) (rate(cortex_prometheus_rule_evaluations_total[1m])) > 0.01
          for: 5m
          labels:
            severity: warning
          annotations:
            message: |
                Cortex Ruler {{ $labels.instance }} is experiencing {{ printf "%.2f" $value }}% errors for the rule group {{ $labels.rule_group }}.
        - alert: "CortexRulerMissedEvaluations"
          expr: |-
            sum by(cluster, namespace, instance, rule_group) (rate(cortex_prometheus_rule_group_iterations_missed_total[1m])) / sum by(cluster, namespace, instance, rule_group) (rate(cortex_prometheus_rule_group_iterations_total[1m])) > 0.01
          for: 5m
          labels:
            severity: warning
          annotations:
            message: |
                Cortex Ruler {{ $labels.instance }} is experiencing {{ printf "%.2f" $value }}% missed iterations for the rule group {{ $labels.rule_group }}.
        - alert: "CortexRulerFailedRingCheck"
          expr: |-
            sum by(cluster, namespace) (rate(cortex_ruler_ring_check_errors_total[5m])) > 0
          for: 1m
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.job }} is experiencing {{ printf "%.2f" $value }}% errors when checking the ring for rule group ownership.
    - name: gossip_alerts
      rules:
        - alert: "CortexGossipMembersMismatch"
          expr: |-
            memberlist_client_cluster_members_count != on(cluster, namespace) group_left() sum by(cluster, namespace) (up{job=~".+/(distributor|ingester|querier|cortex|ruler)"})
          for: 5m
          labels:
            severity: warning
          annotations:
            message: '{{ $labels.job }}/{{ $labels.instance }} sees incorrect number of gossip members.'
    - name: cortex_blocks_alerts
      rules:
        - alert: "CortexIngesterHasNotShippedBlocks"
          expr: |-
            (min by(namespace, instance, cluster) (time() - thanos_objstore_bucket_last_successful_upload_time{job=~".+/ingester"}) > 60 * 60 * 4) and (max by(namespace, instance, cluster) (thanos_objstore_bucket_last_successful_upload_time{job=~".+/ingester"}) > 0) and (max by(namespace, instance, cluster) (rate(cortex_ingester_ingested_samples_total[4h])) > 0)
          for: 15m
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} has not shipped any block in the last 4 hours.
        - alert: "CortexIngesterHasNotShippedBlocksSinceStart"
          expr: |-
            (max by(namespace, instance, cluster) (thanos_objstore_bucket_last_successful_upload_time{job=~".+/ingester"}) == 0) and (max by(namespace, instance, cluster) (rate(cortex_ingester_ingested_samples_total[4h])) > 0)
          for: 4h
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} has not shipped any block in the last 4 hours.
        - alert: "CortexIngesterTSDBHeadCompactionFailed"
          expr: |-
            rate(cortex_ingester_tsdb_compactions_failed_total[5m]) > 0
          for: 15m
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} is failing to compact TSDB head.
        - alert: "CortexIngesterTSDBHeadTruncationFailed"
          expr: |-
            rate(cortex_ingester_tsdb_head_truncations_failed_total[5m]) > 0
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} is failing to truncate TSDB head.
        - alert: "CortexIngesterTSDBCheckpointCreationFailed"
          expr: |-
            rate(cortex_ingester_tsdb_checkpoint_creations_failed_total[5m]) > 0
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} is failing to create TSDB checkpoint.
        - alert: "CortexIngesterTSDBCheckpointDeletionFailed"
          expr: |-
            rate(cortex_ingester_tsdb_checkpoint_deletions_failed_total[5m]) > 0
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} is failing to delete TSDB checkpoint.
        - alert: "CortexIngesterTSDBWALTruncationFailed"
          expr: |-
            rate(cortex_ingester_tsdb_wal_truncations_failed_total[5m]) > 0
          labels:
            severity: warning
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} is failing to truncate TSDB WAL.
        - alert: "CortexIngesterTSDBWALCorrupted"
          expr: |-
            rate(cortex_ingester_tsdb_wal_corruptions_total[5m]) > 0
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} got a corrupted TSDB WAL.
        - alert: "CortexIngesterTSDBWALWritesFailed"
          expr: |-
            rate(cortex_ingester_tsdb_wal_writes_failed_total[1m]) > 0
          for: 3m
          labels:
            severity: critical
          annotations:
            message: Cortex Ingester {{ $labels.namespace }}/{{ $labels.instance }} is failing to write to TSDB WAL.
        - alert: "CortexQuerierHasNotScanTheBucket"
          expr: |-
            (time() - cortex_querier_blocks_last_successful_scan_timestamp_seconds > 60 * 30) and cortex_querier_blocks_last_successful_scan_timestamp_seconds > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            message: Cortex Querier {{ $labels.namespace }}/{{ $labels.instance }} has not successfully scanned the bucket since {{ $value | humanizeDuration }}.
        - alert: "CortexQuerierHighRefetchRate"
          expr: |-
            100 * ((sum by(namespace, cluster) (rate(cortex_querier_storegateway_refetches_per_query_count[5m])) - sum by(namespace, cluster) (rate(cortex_querier_storegateway_refetches_per_query_bucket{le="0"}[5m]))) / sum by(namespace, cluster) (rate(cortex_querier_storegateway_refetches_per_query_count[5m]))) > 1
          for: 10m
          labels:
            severity: warning
          annotations:
            message: Cortex Queries in {{ $labels.namespace }} are refetching series from different store-gateways (because of missing blocks) for the {{ printf "%.0f" $value }}% of queries.
        - alert: "CortexStoreGatewayHasNotSyncTheBucket"
          expr: |-
            (time() - cortex_bucket_stores_blocks_last_successful_sync_timestamp_seconds{component="store-gateway"} > 60 * 30) and cortex_bucket_stores_blocks_last_successful_sync_timestamp_seconds{component="store-gateway"} > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            message: Cortex Store Gateway {{ $labels.namespace }}/{{ $labels.instance }} has not successfully synched the bucket since {{ $value | humanizeDuration }}.
    - name: cortex_compactor_alerts
      rules:
        - alert: "CortexCompactorHasNotSuccessfullyCleanedUpBlocks"
          expr: |-
            (time() - cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds > 60 * 60 * 24) and (cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds > 0)
          for: 15m
          labels:
            severity: critical
          annotations:
            message: Cortex Compactor {{ $labels.namespace }}/{{ $labels.instance }} has not successfully cleaned up blocks in the last 24 hours.
        - alert: "CortexCompactorHasNotSuccessfullyCleanedUpBlocksSinceStart"
          expr: |-
            cortex_compactor_block_cleanup_last_successful_run_timestamp_seconds == 0
          for: 1d
          labels:
            severity: critical
          annotations:
            message: Cortex Compactor {{ $labels.namespace }}/{{ $labels.instance }} has not successfully cleaned up blocks in the last 24 hours.
        - alert: "CortexCompactorHasNotUploadedBlocks"
          expr: |-
            (time() - thanos_objstore_bucket_last_successful_upload_time{job=~".+/compactor"} > 60 * 60 * 24) and (thanos_objstore_bucket_last_successful_upload_time{job=~".+/compactor"} > 0)
          for: 15m
          labels:
            severity: critical
          annotations:
            message: Cortex Compactor {{ $labels.namespace }}/{{ $labels.instance }} has not uploaded any block in the last 24 hours.
        - alert: "CortexCompactorHasNotUploadedBlocksSinceStart"
          expr: |-
            thanos_objstore_bucket_last_successful_upload_time{job=~".+/compactor"} == 0
          for: 1d
          labels:
            severity: critical
          annotations:
            message: Cortex Compactor {{ $labels.namespace }}/{{ $labels.instance }} has not uploaded any block in the last 24 hours.
        - alert: "CortexCompactorRunFailed"
          expr: |-
            increase(cortex_compactor_runs_failed_total[2h]) > 1
          labels:
            severity: critical
          annotations:
            message: |
                {{ $labels.job }}/{{ $labels.instance }} failed to run compaction.
