kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx
data:
  nginx.conf: |-
    worker_processes  5;  ## Default: 1
    error_log  /dev/stderr;
    pid        /tmp/nginx.pid;
    worker_rlimit_nofile 8192;

    events {
      worker_connections  4096;  ## Default: 1024
    }

    http {
      default_type application/octet-stream;
      log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log   /dev/stderr  main;
      sendfile     on;
      tcp_nopush   on;
      resolver kube-dns.kube-system.svc.cluster.local;

      server { # simple reverse-proxy
        listen 80;
        proxy_set_header X-Scope-OrgID 0;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;

        location = /healthz {
          return 200 'alive';
        }

        # Distributor Config
        location = /ring {
          proxy_pass      http://distributor.cortex-k8s.svc.cluster.local$request_uri;
        }

        location = /all_user_stats {
          proxy_pass      http://distributor.cortex-k8s.svc.cluster.local$request_uri;
        }

        location = /api/prom/push {
          proxy_pass      http://distributor.cortex-k8s.svc.cluster.local$request_uri;
        }

        # Query Config
        location ~ /api/prom/.* {
          proxy_pass      http://query-frontend.cortex-k8s.svc.cluster.local$request_uri;
        }

        # Alertmanager Config
        location ~ /api/prom/alertmanager/.* {
          proxy_pass      http://alertmanager.cortex-k8s.svc.cluster.local$request_uri;
        }

        location ~ /api/v1/alerts {
          proxy_pass      http://alertmanager.cortex-k8s.svc.cluster.local$request_uri;
        }

        location ~ /multitenant_alertmanager/status {
          proxy_pass      http://alertmanager.cortex-k8s.svc.cluster.local$request_uri;
        }

        # Ruler Config
        location ~ /api/v1/rules {
          proxy_pass      http://ruler.cortex-k8s.svc.cluster.local$request_uri;
        }

        location ~ /ruler/ring {
          proxy_pass      http://ruler.cortex-k8s.svc.cluster.local$request_uri;
        }

        # Config Config
        location ~ /api/prom/configs/.* {
          proxy_pass      http://configs.cortex-k8s.svc.cluster.local$request_uri;
        }
      }
    }
