---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: /minio/prometheus/metrics
        prometheus.io/port: "9000"
        prometheus.io.scrape: "true"
    spec:
      containers:
      - name: minio
        image: minio/minio
        # Create the "cortex" bucket before starting minio server.
        command: [ "sh", "-c", "mkdir /storage/cortex && minio server /storage"]
        env:
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          value: "public"
        - name: MINIO_ACCESS_KEY
          value: "cortex"
        - name: MINIO_SECRET_KEY
          value: "supersecret"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          name: http-metrics
        volumeMounts:
        - name: storage
          mountPath: "/storage"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: cortex-s3