---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: store-gateway
  name: store-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      name: store-gateway
  serviceName: store-gateway
  template:
    metadata:
      labels:
        name: store-gateway
      annotations:
        prometheus.io.scrape: "true"
        prometheus.io.port: "80"
    spec:
      containers:
      - name: store-gateway
        image: quay.io/cortexproject/cortex:v1.5.0
        imagePullPolicy: IfNotPresent
        env:
          - name: JAEGER_AGENT_HOST
            value: jaeger-agent-svc
          - name: JAEGER_AGENT_PORT
            value: "6831"
          - name: JAEGER_TAGS
            value: app=store-gateway
          - name: JAEGER_SAMPLER_TYPE
            value: const
          - name: JAEGER_SAMPLER_PARAM
            value: "1"
        args:
        - -blocks-storage.bucket-store.metadata-cache.backend=memcached
        - -blocks-storage.bucket-store.metadata-cache.memcached.addresses=memcached.cortex-k8s.svc.cluster.local:11211
        - -blocks-storage.bucket-store.index-cache.backend=memcached
        - -blocks-storage.bucket-store.index-cache.memcached.addresses=memcached.cortex-k8s.svc.cluster.local:11211
        - -blocks-storage.bucket-store.chunks-cache.backend=memcached
        - -blocks-storage.bucket-store.chunks-cache.memcached.addresses=memcached.cortex-k8s.svc.cluster.local:11211
        - -blocks-storage.bucket-store.ignore-deletion-marks-delay=1h
        - -blocks-storage.bucket-store.sync-dir=/data/tsdb
        - -blocks-storage.backend=s3
        - -blocks-storage.s3.bucket-name=cortex
        - -blocks-storage.s3.access-key-id=cortex
        - -blocks-storage.s3.secret-access-key=supersecret
        - -blocks-storage.s3.endpoint=s3.cortex-k8s.svc.cluster.local:9000
        - -blocks-storage.s3.insecure=true
        - -blocks-storage.tsdb.block-ranges-period=2h
        - -blocks-storage.tsdb.dir=/data/tsdb
        - -blocks-storage.tsdb.retention-period=96h
        - -blocks-storage.tsdb.ship-interval=1m
        - -consul.hostname=consul.cortex-k8s.svc.cluster.local:8500
        - -log.level=warn
        - -s3.url=s3://cortex:supersecret@s3.cortex-k8s.svc.cluster.local:9000/cortex
        - -s3.force-path-style=true
        - -server.grpc-max-concurrent-streams=100000
        - -store-gateway.sharding-enabled=true
        - -store-gateway.sharding-strategy=shuffle-sharding
        - -store-gateway.tenant-shard-size=1
        - -store-gateway.sharding-ring.consul.hostname=consul.cortex-k8s.svc.cluster.local:8500
        - -store-gateway.sharding-ring.prefix=
        - -store-gateway.sharding-ring.store=consul
        - -store.engine=blocks
        - -target=store-gateway
        readinessProbe:
          httpGet:
            port: 80
            path: /ready
        ports:
          - name: http-metrics
            containerPort: 80
            protocol: TCP
          - name: grpc-store-gw
            containerPort: 9095
            protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: store-gateway
      volumes:
      - name: store-gateway
        persistentVolumeClaim:
          claimName: store-gateway
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: store-gateway
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn