---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  ports:
  - port: 8080
    name: http-metrics
  - port: 9095
    name: grpc-am
  selector:
    app: alertmanager