---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-headless
  labels:
    app: alertmanager
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 8080
    name: http-metrics
  - port: 9093
    name: http-web
  - port: 9094
    name: tcp-cluster
  - port: 9094
    protocol: UDP
    name: udp-cluster
  - port: 9095
    name: grpc-am
  selector:
    app: alertmanager