---
apiVersion: v1
kind: Service
metadata:
  name: compactor
  labels:
    app: compactor
spec:
  ports:
  - port: 8080
    name: http-metrics
  - port: 9095
    name: grpc-compactor
  selector:
    app: compactor