---
apiVersion: v1
kind: Service
metadata:
  name: gossip-ring-headless
  labels:
    app: gossip-ring
    prometheus.io/service-monitor: "false"
spec:
  clusterIP: None
  ports:
  - name: tcp-gossip-ring
    port: 7946
    protocol: TCP
    targetPort: 7946
  publishNotReadyAddresses: true
  selector:
    gossip_ring_member: "true"