---
apiVersion: v1
kind: Service
metadata:
  name: ingester-headless
  labels:
    app: ingester
    prometheus.io/service-monitor: "false"
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 8080
  - name: grpc-ingester
    port: 9095
  selector:
    app: ingester