---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingester
  labels:
    app: ingester
spec:
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: ingester
  serviceName: ingester-headless
  template:
    metadata:
      labels:
        app: ingester
        gossip_ring_member: "true"
    spec:
      containers:
      - name: ingester
        image: grafana/mimir
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: mimir-env
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - -target=ingester
        - -config.expand-env=true
        - -config.file=/etc/mimir/mimir.yaml
        - -ingester.ring.instance-availability-zone=zone-default
        - -memberlist.bind-addr=$(POD_IP)
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 60
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 9095
          name: grpc-ingester
        - containerPort: 7946
          name: http-memberlist
        volumeMounts:
        - mountPath: /etc/mimir
          name: mimir-config
        - mountPath: /var/mimir
          name: runtime-config
      terminationGracePeriodSeconds: 240
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
      - name: runtime-config
        configMap:
          name: runtime-config