---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: nginx-env
        ports:
        - name: http-service
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: http-service
          initialDelaySeconds: 15
          timeoutSeconds: 1
        volumeMounts:
        - name: templates
          mountPath: /etc/nginx/templates
      terminationGracePeriodSeconds: 30
      volumes:
      - name: templates
        configMap:
          name: nginx-templates