---
apiVersion: v1
kind: Service
metadata:
  name: query-scheduler
  labels:
    app: query-scheduler
spec:
  ports:
  - port: 8080
    name: http-metrics
  - port: 9095
    name: grpc-scheduler
  selector:
    app: query-scheduler