---
apiVersion: v1
kind: Service
metadata:
  name: store-gateway-headless
  labels:
    app: store-gateway
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: http-metrics
  - port: 9095
    name: grpc-store-gw
  selector:
    app: store-gateway