---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: store-gateway
  labels:
    app: store-gateway
spec:
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: store-gateway
  serviceName: store-gateway-headless
  template:
    metadata:
      labels:
        app: store-gateway
        gossip_ring_member: "true"
    spec:
      containers:
      - name: store-gateway
        image: grafana/mimir
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: mimir-env
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - -target=store-gateway
        - -config.file=/etc/mimir/mimir.yaml
        - -config.expand-env=true
        - -memberlist.bind-addr=$(POD_IP)
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 60
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        - name: grpc-store-gw
          containerPort: 9095
          protocol: TCP
        - containerPort: 7946
          name: http-memberlist
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/mimir
          name: mimir-config
        - mountPath: /var/mimir
          name: runtime-config
      terminationGracePeriodSeconds: 240
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
      - name: runtime-config
        configMap:
          name: runtime-config